### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by lordksix** [lordksix/Meals-API-template#121]
The Capstone Project was set up as follows:
- location: https://github.com/lordksix/Meals-API-template/projects/1
- members of the team: 2

**Comment by AbelG101** [comment]
![](https://media.giphy.com/media/eKfovWZOlOpbTDEX9F/giphy.gif)

# Hi @lordksix &  @AbdelazizSoliman  👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- All project cards are present ✔
- Kanban board is setup completely ✔

## Optional suggestions
- Please make sure you submit a complete request, I noticed you guys fixed the group tasks assignment after requesting a review. It's fine but If I hadn't checked for the 2nd time this could cause anomalies in reviews. ✔

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
