### ISSUE TITLE
Peer To Peer 5/26/2023

### ISSUE THREAD

**Issue by waelelsafty07** [lordksix/Meals-API-template#133]
Hi @lordksix 

Good Work 💯  
https://github.com/lordksix/Meals-API-template/blob/ca7e81d38afa39c48ab40f42a9db40ada6b44fd1/src/modules/ListItemMod.js#L20
but I find something above not clear about full classes[7] here I don't know what's means. 
https://github.com/lordksix/Meals-API-template/blob/76e11b8d79b7e0e57388a2e77e485c4064927d7d/src/modules/const.js#L10-L13
I suggest converting the above code export classes from `array` to `object` to fix `classes[7]` to `classes.classBtn`
by doing the above thing it will be more readable

also, I put my resource for clean code the book called clean code for **[Robert C. Martin](https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882)**

**Comment by lordksix** [comment]
Thanks! I have made add the suggestions to the code. @waelelsafty07
